; ────────────── Gammastep Configuration ──────────────
; Lệnh restart Gammastep nhanh trong terminal:
;   pkill -9 gammastep; gammastep &
;
; Lệnh restart và xem log chi tiết (Verbose mode):
;   pkill -9 gammastep; gammastep -v
; ─────────────────────────────────────────────────────

[general]
temp-day=25000
temp-night=3500
fade=1
gamma=1.0
location-provider=manual
adjustment-method=wayland

[manual]
lat=13.78
lon=109.22
